### PR TITLE
Feature scraper automation

### PR DESCRIPTION
**Pull request by tomarken**
Hello VILF Nation,

I've made a simple utility `spatula` that scrapes Google maps with both an interactive and manual mode to gather restaurant metadata and write to a markdown file. I've tried my best to make this easy to use for casual contributors with a CLI. Details and examples are in the updated readme. I have unit tested most of the scraper class during development (tests not in this pull request) and I've also run through about 20-30 restaurants that are in the VILF database with success in the interactive search mode. More than happy to hear pushback or other ideas about how to integrate similar features.

### CODE REVIEW

**Review by ItsiW — APPROVED** [review]
This is so good, works a treat. I'm gonna submit a bunch of reviews I've been putting off with this.

Was it a purposeful decision to not default the new file into `places/`?

**Comment by tomarken** [comment]
> This is so good, works a treat. I'm gonna submit a bunch of reviews I've been putting off with this.
> 
> Was it a purposeful decision to not default the new file into `places/`?

Great to hear! That's a good point about defaulting to `places`. I was not 100% sure how people would use this script. If you were to call it from a different location, e.g. from your OS home directory `python repos/VILF/spatula.py ...`, if the default is `./places` then this would generate new directory `~/places` for the output. This could get confusing if this wasn't intended, but I do think it's likely people would mostly run this from the repo home directory in which case making `places` the default would be smart. Happy to change it (leaning towards changing now), but your call.

**Comment by ItsiW** [comment]
I think we're going to make a separate google form for most contributors as most don't even have gh accounts, it's probably safe to assume that people using this will likely be running vilf locally to test it in any case so they're likely in the repo home dir. Yeah let's change it if you don't mind

**Comment by ItsiW** [comment]
Cheers, feel free to merge

**Comment by tomarken** [comment]
> Cheers, feel free to merge

I don't think I have write access on the repo. Feel free to merge whenever you want.

**Pull request merged**
