### PR TITLE
Fix scrape fail

### PR DESCRIPTION
**Pull request by tomarken**
Wrote a script to run every current entry in VILF through `spatula` to check for edge cases (used a search of the form '[name] restaurant at [address] in [area]'. I found a few places for improvement and also found a handful of potential errors in the markdown files as a result. 

Main changes:
- Refactored `scrape` so that it catches the possibility that a search result returns a valid location but it doesn't have an address (e.g. 'Battambang' is a city in Cambodia and won't return an address). Now, if parsing returns an error it encourages the user to perform a new search instead of crashing (e.g. 'Battambang Oakland' or 'Battambang restaurant' are enough info for Google)
- Changed the address parsing. I'm now regexing for a leading digit (signaling street address) and the state/zip to provide some bounds on where to search. This allows you to throw away extraneous info added before the street address (e.g. inside mall, 122 A St). If it doesn't find a leading digit, it falls back to using everything from the beginning to cover weird edge cases like 'One Ferry Building, The Embarcadero S'.
- Added a close method
- Removing punctuation in the filename
- Found what I believe to be corrections to already existing markdown

### CODE REVIEW

**Comment by tomarken** [comment]
@ItsiW this is ready for review, I seem to be unable to add a reviewer after-the-fact... maybe because I'm not a project contributor? Sorry, I'm more familiar with GitLab's interface.

**Comment by ItsiW** [comment]
Sorry forgot to add you as a collaborator. You should be able to use everything as expected now (adding reviewers, merging, etc.)

But looks great, is checking through all the files a script we can use in the future? Might be something good to run once a month or something

**Review by ItsiW — APPROVED** [review]

**Comment by tomarken** [comment]
> Sorry forgot to add you as a collaborator. You should be able to use everything as expected now (adding reviewers, merging, etc.)

Thanks!

> But looks great, is checking through all the files a script we can use in the future? Might be something good to run once a month or something

Yes, I could see this being useful potentially. I've added the `cross_reference.py` script. I'm not sure if you picture this fitting into the repo in the longterm - it's not that fast so it wouldn't scale well once there are many reviews, but it was still useful for catching errors (I ignored mild formatting differences and just corrected typos and incorrect addresses).

Do you have a preference for file structure of the python content? I stuck `spatula.py` in the home directory so the command line calls would be less cumbersome, but if you want to include `cross_reference.py` in the pull request, might make sense to bundle these together somewhere. I wasn't sure if there might be a `python` directory at some point to silo the python content from the HTML.

**Comment by ItsiW** [comment]
Oops forgot to get back to you on this. Maybe we could run it on the dif files as part of the tests for a new branch, and throw up flags?

In regards to structure, I have no experience or opinions in this, maybe @schradert does?

**Comment by ItsiW** [comment]
Hey could you double check the scraping for lat and lon? I'm running some new ones and looks like it's getting some wrong, like 10 blocks away, even when the google link it provides is correct. E.g. Itani Ramen and Maya Halal Taqueria

**Comment by tomarken** [comment]
> Hey could you double check the scraping for lat and lon? I'm running some new ones and looks like it's getting some wrong, like 10 blocks away, even when the google link it provides is correct. E.g. Itani Ramen and Maya Halal Taqueria

Yes, I can reproduce this. If you paste the URL it finds into your browser and watch the lat/lon in the URL it redirects after about a second. This is because Google Maps first redirects to a page with approximate lat/lon (which is triggering my wait for redirect to succeed) and then updates after a second or two to better coords. I might have to add a fixed dead time to account for this, was hoping to avoid that but I'm not sure it'll be easy to distinguish when the coords are correct. I'll play around with it and see what I can come up with.

**Comment by tomarken** [comment]
> Hey could you double check the scraping for lat and lon? I'm running some new ones and looks like it's getting some wrong, like 10 blocks away, even when the google link it provides is correct. E.g. Itani Ramen and Maya Halal Taqueria

Actually it seems the lat/lon are placed in two locations in the URL, one is between '@' and ',' and then at the end of the URL. The one at the end seems to be the correct location (maybe this is cached). It would be easy to use the end of the URL for the lat and lon. I'll try several locations to make sure this is generally true.

**Comment by tomarken** [comment]
@ItsiW it turns out the lat/lon from the URL that I was grabbing correspond to the center of the map, not the restaurant's lat/lon. That info is actually at the end of the URL in a different place. When I was testing earlier, those are frequently the same and I didn't catch that they represent different data. I have now fixed this to regex against the correct location. Also I made `cross_reference` a click-based CLI so you can run something like:
```
python cross_reference.py $(git diff --staged --name-only places/)

Testing files:
✘ places/lion-dance-cafe.md
✔ places/maya-halal-taqueria.md

The following files may need inspection:

places/lion-dance-cafe.md
Current address: 382 17th St | Determined address: 380 17th St
Current latitude: 34.8060489 | Determined latitude: 37.8060489
Current longitude: -120.267932 | Determined longitude: -122.267932
```

**Comment by schradert** [comment]
> Oops forgot to get back to you on this. Maybe we could run it on the dif files as part of the tests for a new branch, and throw up flags?
> 
> In regards to structure, I have no experience or opinions in this, maybe @schradert does?

We could have a `vilf/` directory for Python scripts (very typical for most Python projects), and ideally I think all the scripts would be available through the same CLI. The usage could look like `vilf build`, `vilf scrape URL`, and `vilf check FILE [FILE ...]`. The repo is small enough at this point still though that I don't really care. Sorry I've been absent from the conversation.

**Comment by tomarken** [comment]
> > Oops forgot to get back to you on this. Maybe we could run it on the dif files as part of the tests for a new branch, and throw up flags?
> > In regards to structure, I have no experience or opinions in this, maybe @schradert does?
> 
> We could have a `vilf/` directory for Python scripts (very typical for most Python projects), and ideally I think all the scripts would be available through the same CLI. The usage could look like `vilf build`, `vilf scrape URL`, and `vilf check FILE [FILE ...]`. The repo is small enough at this point still though that I don't really care. Sorry I've been absent from the conversation.

I like this suggestion a lot @schradert. I took a stab at making something like this using the `click` module. Short of defining an alias for `vilf`, which I was trying to avoid so new contributors won't need to edit their `PATH`, the closest I could get was defining a local shell script `vilf.sh` to recreate the same ergonomics. If you know of a better way, I'd be interested to know. This script just passes any args to `python -m scripts.cli ARGS` which can currently handle `build`, `spatula`, and `check`. I moved `build.py` to `scripts` and nested everything inside one large function in order to expose it to `click`. Obviously feel free to make any changes or object if you didn't picture something like this.   

Root CLI:
```bash
~/repos/VILFtomarken (fix-scrape-fail*) » ./vilf.sh --help        
Usage: python -m scripts.cli [OPTIONS] COMMAND [ARGS]...

  VILF CLI

Options:
  --help  Show this message and exit.

Commands:
  build    Build VILF locally.
  check    Cross-reference the files against scraped Google Maps
  spatula  Scrape Google Maps and generate a markdown file
```

**Comment by ItsiW** [comment]
Sick, thanks for working through all of this. Just want to double-check that gcp is going to know where to find build.py now that it's moved, but otherwise let's merge this stuff.

**Comment by tomarken** [comment]
> Sick, thanks for working through all of this. Just want to double-check that gcp is going to know where to find build.py now that it's moved, but otherwise let's merge this stuff.

Sounds good! I was able to build and serve locally in case that's relevant.

**Comment by schradert** [comment]
You'll need to make an edit to [.github/workflows/deploy.yaml](https://github.com/ItsiW/VILF/blob/15190705d7fb82075d27334fb2205b2b7871663e/.github/workflows/deploy.yaml#L11) from `python3 build.py` to `./vilf.sh build`. This will build the website correctly in the GitHub automation just as before using this redesign. This step is independent of how GCP serves these static files.

To ensure it builds on merging your pull request too, I just realized we need to add two lines to the same GitHub Action configuration so it looks like so:

```yaml
...
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
...
```

After these changes, I think you'll be good to merge.

**Comment by tomarken** [comment]
Changing the shell from zsh -> bash in `vilf.sh` fixed the initial failure to build, but now it's failing since I'm on a fork and it won't load the secret (makes sense). In the future I think this should work with pull requests as long as I'm branching instead of forking. 
```
Error: google-github-actions/auth failed with: retry function failed after 1 attempt: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.
```

**Pull request merged**
